# Generated by Django 3.1.2 on 2020-11-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='join_users',
        ),
    ]
