# Generated by Django 3.1.2 on 2020-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_remove_summary_join_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='text',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='title',
        ),
        migrations.AddField(
            model_name='summary',
            name='category_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='section_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='url',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
