# Generated by Django 3.1.2 on 2020-11-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201107_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
