# Generated by Django 3.1.2 on 2020-11-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postthum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostThum',
        ),
    ]
